# Generated by Django 3.2 on 2023-01-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('MOD', 'moderator'), ('ADM', 'admin')], default='user', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
